name: Debug CI

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  debug:
    name: Debug Environment
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Check Node version
      run: node --version
      
    - name: Check npm version
      run: npm --version
      
    - name: List workspace files
      run: |
        echo "Root directory:"
        ls -la
        echo ""
        echo "Server directory:"
        ls -la server/
        echo ""
        echo "Package.json contents:"
        cat package.json | head -20
        echo ""
        echo "Server package.json contents:"
        cat server/package.json | head -20
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
        cache-dependency-path: |
          package-lock.json
          server/package-lock.json
        
    - name: Test frontend npm ci
      run: |
        echo "Installing frontend dependencies..."
        npm ci
        echo "Frontend dependencies installed successfully"
        
    - name: Test frontend build
      run: |
        echo "Building frontend..."
        npm run build
        echo "Frontend built successfully"
        
    - name: Test frontend tests
      run: |
        echo "Running frontend tests..."
        CI=true npm test -- --watchAll=false
        echo "Frontend tests completed"
        
    - name: Test backend npm ci
      run: |
        echo "Installing backend dependencies..."
        cd server
        npm ci
        echo "Backend dependencies installed successfully"
        
    - name: Test backend type-check
      run: |
        echo "Running backend type check..."
        cd server
        npm run type-check
        echo "Backend type check completed"
        
    - name: Test backend tests
      run: |
        echo "Running backend tests..."
        cd server
        npm test
        echo "Backend tests completed"