name: Quick Tests

# This workflow runs on every push for fast feedback
# Use for quick validation of changes
on:
  push:
    paths:
      - 'server/**'
      - '.github/workflows/quick-test.yml'

jobs:
  quick-test:
    name: Quick Backend Tests
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        
    - name: Install dependencies
      run: |
        cd server
        npm ci
        
    - name: Run tests
      run: |
        cd server
        npm test
        
    - name: Quick status check
      run: |
        echo "✅ All tests passing! Ready for development." >> $GITHUB_STEP_SUMMARY