name: Quick Tests

# This workflow runs on every push for fast feedback
# Use for quick validation of changes
on:
  push:
    paths:
      - 'server/**'
      - 'src/**'
      - 'package.json'
      - 'package-lock.json'
      - '.github/workflows/**'

env:
  CI: true

jobs:
  quick-test:
    name: Quick Tests
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22.x'
        
    - name: Install frontend dependencies
      run: npm ci
        
    - name: Run frontend tests
      run: npm test -- --watchAll=false --passWithNoTests
        
    - name: Build frontend
      run: npm run build
        
    - name: Install backend dependencies
      run: |
        cd server
        npm ci
        
    - name: TypeScript compilation check
      run: |
        cd server
        npm run build
        
    - name: Quick status check
      run: |
        echo "✅ Frontend tests and build successful"
        echo "✅ Backend TypeScript compilation successful"
        echo "ℹ️  Billable hours regression tests run in full CI only"